### ISSUE TITLE
install fails on iojs3.0

### ISSUE THREAD

**Issue by notthetup** [zaro/node-htmlstrip-native#15]
`node-gyp` install fails for iojs3.0 as v8 API changed.

Seems like the `Object::GetIndexedPropertiesExternalArrayData` API was removed. I can't seem to find any documentation on what it was replaced with. :(

```
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/htmlstrip/htmlstrip.o
In file included from ../htmlstrip.cpp:5:
../entities.hpp:82:3: warning: 'register' storage class specifier is deprecated [-Wdeprecated-register]
  register int hval = len;
  ^~~~~~~~~
../entities.hpp:2365:7: warning: 'register' storage class specifier is deprecated
      [-Wdeprecated-register]
      register int key = hash (str, len);
      ^~~~~~~~~
../entities.hpp:2369:11: warning: 'register' storage class specifier is deprecated
      [-Wdeprecated-register]
          register const struct entity *resword;
          ^~~~~~~~~
../entities.hpp:9073:13: warning: 'register' storage class specifier is deprecated
      [-Wdeprecated-register]
            register const char *s = resword->name;
            ^~~~~~~~~
../htmlstrip.cpp:272:15: error: no member named 'GetIndexedPropertiesExternalArrayData' in 'v8::Object'
                        outBuffer->GetIndexedPropertiesExternalArrayData());
                        ~~~~~~~~~  ^
../htmlstrip.cpp:533:15: error: no member named 'GetIndexedPropertiesExternalArrayData' in 'v8::Object'
                        outBuffer->GetIndexedPropertiesExternalArrayData());
                        ~~~~~~~~~  ^
../htmlstrip.cpp:550:16: error: no member named 'GetIndexedPropertiesExternalArrayData' in 'v8::Object'
                                outBuffer->GetIndexedPropertiesExternalArrayData()))
                                ~~~~~~~~~  ^
../htmlstrip.cpp:129:46: note: expanded from macro 'NEW_INTEGER'
#define NEW_INTEGER(x) Integer::New(isolate, x)
                                             ^
../htmlstrip.cpp:581:15: error: no member named 'GetIndexedPropertiesExternalArrayData' in 'v8::Object'
                        outBuffer->GetIndexedPropertiesExternalArrayData());
                        ~~~~~~~~~  ^
../htmlstrip.cpp:593:16: error: no member named 'GetIndexedPropertiesExternalArrayData' in 'v8::Object'
                                outBuffer->GetIndexedPropertiesExternalArrayData()))
                                ~~~~~~~~~  ^
../htmlstrip.cpp:129:46: note: expanded from macro 'NEW_INTEGER'
#define NEW_INTEGER(x) Integer::New(isolate, x)
                                             ^
../htmlstrip.cpp:624:15: error: no member named 'GetIndexedPropertiesExternalArrayData' in 'v8::Object'
                        outBuffer->GetIndexedPropertiesExternalArrayData());
                        ~~~~~~~~~  ^
../htmlstrip.cpp:636:16: error: no member named 'GetIndexedPropertiesExternalArrayData' in 'v8::Object'
                                outBuffer->GetIndexedPropertiesExternalArrayData()))
                                ~~~~~~~~~  ^
../htmlstrip.cpp:129:46: note: expanded from macro 'NEW_INTEGER'
#define NEW_INTEGER(x) Integer::New(isolate, x)
```

**Comment by notthetup** [comment]
Ah ha! I found an indication of what's the replacement for `v8::Object:: GetIndexedPropertiesExternalArrayData `. Apparently it's to use `v8:: ArrayBuffer` directly. 

Source : https://github.com/nodejs/node/issues/2308#issuecomment-128164490

**Comment by hooke** [comment]
Confirming the same error when try to install the package with node.js v.4.1.1

**Comment by zaro** [comment]
just released 0.1.2 , should work fine on iojs and node >=3.0.0
